#!/bin/sh /etc/rc.common
# HAUT Network Guard - OpenWrt 服务脚本

START=99
STOP=10
USE_PROCD=1

PROG=/usr/lib/haut-network-guard/main.lua

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/lua "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "haut-network-guard"
}
